# -- Site Configuration --
theme = "hugo-theme-yinyang"
baseURL = "https://bailanwa.dpdns.org/"
defaultContentLanguage = "zh-cn"
title = "Aliom"

enableRobotsTXT = true
summaryLength = 70

buildDrafts = false
buildFuture = false

enableEmoji = true

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS"]
