# 主菜单配置
[[main]]
  name = "主页"
  url = "/"
  weight = 5

[[main]]
  name = "博客"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "分类"
  url = "/categories/"
  weight = 15

[[main]]
  name = "关于我"
  pageRef = "about"
  weight = 20

[[main]]
  name = "GitHub"
  url = "https://github.com/aliom-v"
  weight = 30
