# YinYang 主题配置
description = "一个技术小白的成长笔记"
mainSections = ["posts"]

[author]
  name = "Aliom"
  homepage = "https://github.com/aliom-v"

# 右上角导航链接
[[socials]]
  name = "GitHub"
  link = "https://github.com/aliom-v"

[[socials]]
  name = "关于我"
  link = "/about/"
